version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  web-form-app:
    build:
      context: .
      dockerfile: web-form-app/Dockerfile
    container_name: web-form-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
